version: "3.3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app
    networks:
      - local-net

  nginx:
    build:
      context: ./
    ports:
      - "80:8002"
    depends_on:
      - backend
    networks:
      - local-net

networks:
  local-net:
    driver: bridge