version: "3.3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./backend/app:/app

  nginx:
    container_name: nginx
    build:
      context: ./
    ports:
      - "3000:8002"
    depends_on:
      - backend