version: "3.3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./backend/app:/app

  nginx:
    container_name: nginx
    build:
      context: ./
    ports:
      - "80:80"
    depends_on:
      - burnout-backend
    networks:
      - local-net
networks:
  local-net:
    driver: bridge